eureka:
    client:
        fetchRegistry: true
        service-url:
            default-zone: http://localhost:8761/eureka/
            fetchRegistry: true
logging:
    file:
        max-history: 7
        max-size: 10MB
        name: App.log
    level:
        com:
            dailycodebuffer: TRACE
    pattern:
        console: '%d [%level] %c{1.} [%t] %m%n'
        file: '%d [%level] %c{1.} [%t] %m%n'
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream

spring:
   
    cache:
        cache-names: UserCache
        ehcache:
            config: 'classpath:'
        type: ehcache
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /console
            settings:
                web-allow-others: true
    jackson:
        default-property-inclusion: NON_NULL
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                globally_quoted_identifiers: true
