eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
server:
    port: 8762
spring:
    application:
        name: Zuul


zuul:
    ignored-services: '*'
    routes:
        Movies:
            path: /Movies/**
            service-id: Movies
        Account:
            path: /Account/**
            service-id: Account

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

logging:
    level:
        ROOT: INFO
        org.springframework.web: DEBUG
