eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetchRegistry: true
server:
  port: 8000

spring:
  application:
    name: Movies
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
